name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install apr
      run: sudo apt install -y libapr1-dev libaprutil1-dev libutf8proc-dev
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
